#!/usr/bin/env bash

. $SNAP/helpers/functions

ensure_root

if [ ! -r "${NANOMQ_CONF}" ]; then
	logp "File: ${NANOMQ_CONF} does not exist. Create it with: $ sudo ${SNAP_INSTANCE_NAME}.conf"
	exit 1
fi

exec $@
